# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b2da5da23905ea6fdcba58cdd8dd9a552e3a991df7ba8ab8b1695fb057a3ef7669265b2cd32c4473b9b37a625b9759c6b1ed8585a040846bd3463824d73900d2

test:
  secret_key_base: 4fe3a2a037c09c3142b9e1c1e06cf381442e040072e47b7741a1ce6c84959e30167cdb950c2784ebd7d3dd4aa04abeb9e7f74ce059fdf898ba1cbd767c371497

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
